version: "3.7"

secrets:
  postgres_passwd:
    file: ./secrets/.postgres-passwd

services:
  postgres:
    image: postgres:11.4-alpine
    # for production we don't need to expose ports
      - '5432'
    secrets:
      - postgres_passwd
    environment:
      POSTGRES_USER: SpamWatchAPI
      POSTGRES_DB: SpamWatchAPI
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_passwd
  api:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - '6345:6345'

